import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — Pastor4Life",
  description: "Privacy Policy for the Pastor4Life mobile application.",
};

// Content is verbatim from WEBSITE_PROJECT_CHECKLIST.md Section 8.4, EXCEPT
// the "Support Requests" item under Section 1 — that paragraph is a drafted
// addition (checklist Section 8.4 build note) covering the new /support form's
// data collection, and still needs actual TBMB sign-off before this page is
// published to production. Do not treat its presence here as approval —
// Phase 7/8 deployment is gated separately regardless.
// "Last Updated" intentionally left at the source date; bump it to the real
// publish date at Phase 8 cutover, not before.
export default function Privacy() {
  return (
    <article className="prose prose-neutral mx-auto max-w-3xl px-6 py-16 prose-headings:text-brand-navy prose-a:text-brand-navy sm:py-20">
      <h1>Privacy Policy</h1>
      <p className="text-sm text-brand-navy/60">Last Updated: June 18, 2026</p>

      <p>
        Pastor4Life (&ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;)
        is committed to protecting your privacy. This Privacy Policy
        explains how we collect, use, disclose, and safeguard your
        information when you use the Pastor4Life mobile application (the
        &ldquo;App&rdquo;). By using the App, you agree to the collection
        and use of information in accordance with this policy.
      </p>

      <h2>1. Information We Collect</h2>

      <h3>Account Information</h3>
      <p>
        When you create an account, we collect your email address and
        password (encrypted) to enable authentication and personalize your
        experience.
      </p>

      <h3>Prayer Focus Content</h3>
      <p>
        The App displays organizational prayer items provided by the
        Tennessee Baptist Mission Board. This content is served from
        TBMB&rsquo;s own database and is not submitted or generated by
        users. No personal prayer list data is collected or stored.
      </p>

      <h3>Route Tracking</h3>
      <p>
        If you use route tracking features, the App uses your device&rsquo;s
        built-in motion sensor (pedometer) to count steps and estimate
        walking distance during a prayer route. This data is processed on
        your device using Apple&rsquo;s Core Motion framework. No GPS or
        location data is collected or transmitted to our servers. Route
        duration and estimated mileage are stored in your account to
        support commitment tracking features. Your commitment progress —
        including your selected commitment journey and miles logged toward
        your goal — is also stored in your account.
      </p>

      <h3>Support Requests</h3>
      <p>
        If you submit a support request through our Support page, we
        collect the name, email address, and message you provide. We use
        this information solely to respond to your request and do not use
        it for any other purpose.
      </p>

      <h2>2. How We Use Your Information</h2>
      <p>We use the information we collect to:</p>
      <ul>
        <li>Provide and maintain the App&rsquo;s functionality</li>
        <li>
          Allow access to personalized features (e.g., your route history
          and commitment progress)
        </li>
        <li>Improve user experience and app performance</li>
        <li>Communicate with you regarding updates or support</li>
      </ul>
      <p>We do not use your information for advertising or marketing purposes.</p>

      <h2>3. How We Protect Your Data</h2>
      <p>
        We take your privacy seriously and implement security best
        practices. All personal data — including user account details and
        route activity — is securely stored using Amazon Web Services (AWS)
        infrastructure. AWS provides industry-standard security and
        compliance protocols, including encryption in transit and at rest.
        For more information on how AWS handles data, please refer to the{" "}
        <a
          href="https://aws.amazon.com/privacy/"
          target="_blank"
          rel="noopener noreferrer"
        >
          AWS Privacy Notice
        </a>
        .
      </p>
      <p>We do not sell, rent, or share your data with third parties.</p>

      <h2>4. Data Retention</h2>
      <p>
        We retain your personal information only for as long as your
        account is active or as needed to provide you with the App&rsquo;s
        services. You may request to delete your account and all
        associated data at any time.
      </p>

      <h2>5. Your Rights and Choices</h2>
      <p>You may:</p>
      <ul>
        <li>Access or update your account details in the App</li>
        <li>
          Permanently delete your account and all associated data —
          including route history and commitment progress — through the
          App&rsquo;s Settings screen. This action is immediate and cannot
          be undone.
        </li>
        <li>
          Contact us with privacy-related questions at
          brainstorm.designs.co@gmail.com
        </li>
      </ul>

      <h2>6. Children&rsquo;s Privacy</h2>
      <p>
        The App is not directed toward children under the age of 13. We do
        not knowingly collect personal information from children. If you
        believe we have unintentionally collected such data, please contact
        us immediately.
      </p>

      <h2>7. Changes to This Privacy Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. Any changes
        will be reflected with a new &ldquo;Last Updated&rdquo; date at the
        top of the policy. We recommend reviewing this page periodically to
        stay informed.
      </p>

      <h2>8. Contact Us</h2>
      <p>
        If you have any questions or concerns about this Privacy Policy,
        please contact us at:
      </p>
      <p>
        Email: brainstorm.designs.co@gmail.com
        <br />
        Website: www.pastor4life.com
      </p>
    </article>
  );
}
